version: '3.8'

services:
  app:
    container_name: cantinho_backend
    image: cantinho_backend:latest
    build: 
      context: ./BACKEND-SPACE
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/space_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=minhasenha123 
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      # URL do Frontend para CORS no backend (se necessário)
      - FRONTEND_URL=https:####################
    depends_on:
      - db
    networks:
      - cantinho-network
    restart: always

  web:
    container_name: cantinho_frontend
    image: cantinho_frontend:latest
    build:
      context: ./FRONEND-SPACE
      dockerfile: Dockerfile
      args:
        # IMPORTANTE: Definir como "/" faz o axios usar o mesmo domínio do site.
        # O Nginx (neste container) vai pegar essas requisições e passar pro backend.
        VITE_API_URL: /
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - cantinho-network
    restart: always

  db:
    container_name: cantinho_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=space_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=minhasenha123 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cantinho-network

networks:
  cantinho-network:
    driver: bridge

volumes:
  postgres_data: